name = "kzora"
author = "nelande"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dcb87563b91b6020af14cada4c3b498a3c7191b0782f9c32408cf34917a8255e"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
