name = "kzora"
author = "nelande"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd42da9e8817be3869ebdeb94fdd1a641c709f08aad015c56c9340ad62a6504e"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
