name = "kzora"
author = "nelande"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa145076dfd5a8d62693ab9264df1839385a2211f28c372bc8bf6384b4299164"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
