name = "kzora"
author = "nelande"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "76db7d732267fa2b0bd5eb65dca67ca10d2af194473d3e9ba14688e2717e0ad0"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
