name = "kzora-server"
author = "nelande"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04366f5e466c9f416f4ae2018801af83592815867f7eb5048914b7d0c6c32dc2"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
