name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install packwiz
        run: |
          curl -sLo packwiz.tar.gz https://github.com/packwiz/packwiz/releases/latest/download/packwiz-linux-amd64.tar.gz
          tar -xzf packwiz.tar.gz
          sudo mv packwiz /usr/local/bin/
          packwiz version

      - name: Run `make update`
        run: make update

      - name: Run `make build`
        run: make build

      - name: Generate timestamp-based tag
        id: tag
        run: echo "tag_name=release-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Upload files from output/ to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag_name }}
          name: Release ${{ steps.tag.outputs.tag_name }}
          files: output/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
