name: Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.kzora-workflow }}  # Personal Access Token с правами repo

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go & packwiz
        run: |
          sudo apt update && sudo apt install -y golang
          go install github.com/packwiz/packwiz@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Run make update
        run: make update

      - name: Run make build
        run: make build

      - name: Install GitHub CLI
        run: sudo apt install -y gh

      - name: Generate tag
        id: tag
        run: echo "TAG=release-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Create Git tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag $TAG
          git push origin $TAG

      - name: Create GitHub Release
        run: |
          gh release create "$TAG" output/* \
            --title "Release $TAG" \
            --notes "Automated build"
